site_name: ""
site_description: binjr Linux repositories
site_url: https://binjr.eu/
copyright: This website is licensed under a Creative Commons Attribution 4.0 International License.
repo_url: ""
edit_uri: ""

nav:
  - Home:
    - https://binjr.eu
  - APT:
    - apt/README.md
  - RPM:
    - rpm/README.md
  - AUR:
    - aur/README.md
  - Winget:
    - winget/README.md  
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - content.code.select
    - content.code.copy
  favicon: https://binjr.eu/assets/images/favicon.png
  logo: https://binjr.eu/assets/images/binjr_logo.png
  highlightjs: true
  hljs_languages:
    - java
    - sh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: octicons/moon-24
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: octicons/sun-24
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - meta
  - smarty
  - extra
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - codehilite:
      guess_lang: False
      use_pygments: True
      noclasses: True
      pygments_style: monokai
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/binjr
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@binjr

